SELECT
Iscrizione.gara,
Iscrizione.tipo,
Atleta.nome,
Atleta.cognome,
Atleta.categoriaFitri,
Atleta.email,
Atleta.telefono,
Atleta.sesso,
Atleta.matricolaFitri,
Atleta.codiceSocietaFitri,
Atleta.pettorale,
Atleta.conclusioneGara,
Atleta.posizione,
Atleta.posizioneInSesso,
Atleta.posizioneInCategoria,
Atleta.tempo,
Atleta.tempoNuoto as tempoDopoNuoto,
Atleta.posizioneNuoto as posizioneDopoNuoto,
Atleta.tempoFrazioneBici,
Atleta.posizioneFrazioneBici,
Atleta.tempoBici as tempoDopoBici,
Atleta.posizioneBici as posizioneDopoBici,
Atleta.tempoFrazioneCorsa,
Atleta.posizioneFrazioneCorsa,
Squadra.nome AS nomeSquadra,
Squadra.pettorale as squadraPettorale,
Squadra.conclusioneGara as squadraConclusioneGara,
Squadra.posizione as squadraPosizione,
Squadra.posizioneInSesso as squadraPosizioneInSesso,
Squadra.posizioneInCategoria as squadraPosizioneInCategoria,
Squadra.tempo as squadraTempo,
Squadra.tempoNuoto as squadraTempoDopoNuoto,
Squadra.posizioneNuoto as squadraPosizioneDopoNuoto,
Squadra.tempoFrazioneBici as squadraTempoFrazioneBici,
Squadra.posizioneFrazioneBici as squadraPosizioneFrazioneBici,
Squadra.tempoBici as squadraTempoDopoBici,
Squadra.posizioneBici as squadraPosizioneDopoBici,
Squadra.tempoFrazioneCorsa as squadraTempoFrazioneCorsa,
Squadra.posizioneFrazioneCorsa as squadraPosizioneFrazioneCorsa

FROM `Atleta` inner join Iscrizione on Atleta.idIscrizione = Iscrizione.id
LEFT JOIN Squadra ON Atleta.idSquadra = Squadra.id

ORDER BY
tipo,
gara,
nomeSquadra